const appData = {
  products: [
    {
      id: "iphone-16-pro-max",
      name: "Apple iPhone 16 Pro Max",
      category: "iPhone",
      description:
        "The ultimate iPhone experience with the most advanced camera system, featuring a 48MP main sensor, periscope telephoto lens, and A18 Pro chip for unprecedented performance.",
      price: 1199.0,
      originalPrice: 1299.0,
      discount: 8,
      inStock: true,
      rating: 4.9,
      reviews: 4231,
      images: ["/iPhone-16-Pro-Max-main.png"],
      thumbnails: ["/iPhone-16-Pro-Max-1.png", "/iPhone-16-Pro-Max-2.png"],
      storage: ["256 GB", "512 GB", "1 TB", "2 TB"],
      colors: ["Space Black", "Silver", "Gold", "Titanium Blue"],
      specifications: {
        display: "6.7-inch Super Retina XDR ProMotion display",
        chip: "A18 Pro chip with 6-core CPU and 5-core GPU",
        camera: "Triple 48MP camera system with periscope telephoto",
        battery: "Up to 32 hours video playback",
        material: "Titanium design with Ceramic Shield",
      },
    },
    {
      id: "iphone-16-plus",
      name: "Apple iPhone 16 Plus",
      category: "iPhone",
      description:
        "The perfect balance of size and performance with a large 6.7-inch display, powerful A17 Bionic chip, and all-day battery life in a sleek design.",
      price: 899.0,
      originalPrice: 999.0,
      discount: 10,
      inStock: true,
      rating: 4.8,
      reviews: 3876,
      images: ["/iPhone 16-Plus-main.png"],
      thumbnails: ["/iPhone-16-Plus-1.png", "/iPhone-16-Plus-2.png"],
      storage: ["128 GB", "256 GB", "512 GB"],
      colors: ["Midnight", "Starlight", "Blue", "Purple", "Red"],
      specifications: {
        display: "6.7-inch Super Retina XDR display",
        chip: "A17 Bionic chip with 5-core GPU",
        camera: "Advanced dual-camera system with 48MP Main",
        battery: "Up to 28 hours video playback",
        water: "IP68 water resistance",
      },
    },
    {
      id: "iphone-15-pro",
      name: "Apple iPhone 15 Pro",
      category: "iPhone",
      description:
        "Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.",
      price: 999.0,
      inStock: true,
      rating: 4.9,
      reviews: 5123,
      images: ["/iphone-15-pro-main.png"],
      thumbnails: ["/iphone-15-pro-1.png", "/iphone-15-pro-2.png"],
      storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
      colors: [
        "Natural Titanium",
        "Blue Titanium",
        "White Titanium",
        "Black Titanium",
      ],
      specifications: {
        display: "6.1-inch Super Retina XDR display with ProMotion",
        chip: "A17 Pro chip with 6-core CPU and 6-core GPU",
        camera: "Pro camera system with 48MP Main",
        battery: "Up to 23 hours video playback",
        material: "Titanium design with Ceramic Shield",
      },
    },
    {
      id: "iphone-14-pro-max",
      name: "Apple iPhone 14 Pro Max",
      category: "iPhone",
      description:
        "The most advanced iPhone with Dynamic Island, Always-On display, and the most advanced Pro camera system.",
      price: 1099.0,
      originalPrice: 1199.0,
      discount: 8,
      inStock: true,
      rating: 4.8,
      reviews: 3567,
      images: ["/iphone-14-pro-max-main.png"],
      thumbnails: ["/iphone-14-pro-max-1.png", "/iphone-14-pro-max-2.png"],
      storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
      colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
      specifications: {
        display: "6.7-inch Super Retina XDR display with ProMotion",
        chip: "A16 Bionic chip with 5-core GPU",
        camera: "Pro camera system with 48MP Main",
        battery: "Up to 29 hours video playback",
        material: "Surgical-grade stainless steel with Ceramic Shield",
      },
    },
    {
      id: "iphone-14",
      name: "Apple iPhone 14",
      category: "iPhone",
      description:
        "Capture stunning photos in low light and bright light with an impressive dual-camera system. Get peace of mind with vital safety features.",
      price: 699.0,
      originalPrice: 799.0,
      discount: 13,
      inStock: true,
      rating: 4.7,
      reviews: 2847,
      images: ["/iphone-14-main.png"],
      thumbnails: ["/iphone-14-1.png", "/iphone-14-2.png"],
      storage: ["128 GB", "256 GB", "512 GB"],
      colors: ["Midnight", "Starlight", "Blue", "Purple", "Red"],
      specifications: {
        display: "6.1-inch Super Retina XDR display",
        chip: "A15 Bionic chip with 5-core GPU",
        camera: "Advanced dual-camera system with 12MP Main",
        battery: "Up to 20 hours video playback",
        water: "IP68 water resistance",
      },
    },
    {
      id: "iphone-13",
      name: "Apple iPhone 13",
      category: "iPhone",
      description:
        "Your new superpower. A15 Bionic, Super Retina XDR display, and up to 19 hours of video playback. Your favorite photos look amazing with Smart HDR 4.",
      price: 599.0,
      originalPrice: 699.0,
      discount: 14,
      inStock: true,
      rating: 4.7,
      reviews: 4278,
      images: ["/iPhone-13-main.png"],
      thumbnails: ["/iPhone-13-1.png", "/iPhone-13-2.png"],
      storage: ["128 GB", "256 GB", "512 GB"],
      colors: ["Midnight", "Starlight", "Blue", "Pink", "Green", "Red"],
      specifications: {
        display: "6.1-inch Super Retina XDR display",
        chip: "A15 Bionic chip with 4-core GPU",
        camera: "Advanced dual-camera system with 12MP Main",
        battery: "Up to 19 hours video playback",
        water: "IP68 water resistance",
      },
    },
    {
      id: "iphone-12",
      name: "Apple iPhone 12",
      category: "iPhone",
      description:
        "A superpowerful chip. 5G speed. An advanced dual-camera system. A Ceramic Shield front that's tougher than any smartphone glass. And a bright, beautiful OLED display.",
      price: 499.0,
      originalPrice: 599.0,
      discount: 17,
      inStock: true,
      rating: 4.6,
      reviews: 3872,
      images: ["/iPhone-12-main.png"],
      thumbnails: ["/iPhone-12-1.png", "/iPhone-12-2.png"],
      storage: ["64 GB", "128 GB", "256 GB"],
      colors: ["Black", "White", "Blue", "Green", "Red", "Purple"],
      specifications: {
        display: "6.1-inch Super Retina XDR display",
        chip: "A14 Bionic chip with 4-core GPU",
        camera: "Dual 12MP camera system with Night mode",
        battery: "Up to 17 hours video playback",
        water: "IP68 water resistance",
      },
    },
    {
      id: "iphone-11",
      name: "Apple iPhone 11",
      category: "iPhone",
      description:
        "A new dual-camera system captures more of what you see and love. The fastest chip ever in a smartphone. All-day battery life. And all-new Night mode.",
      price: 399.0,
      originalPrice: 499.0,
      discount: 20,
      inStock: true,
      rating: 4.5,
      reviews: 5123,
      images: ["/iPhone-11-main.png"],
      thumbnails: ["/iPhone-11-1.png", "/iPhone-11-2.png"],
      storage: ["64 GB", "128 GB", "256 GB"],
      colors: ["Black", "White", "Green", "Yellow", "Purple", "Red"],
      specifications: {
        display: "6.1-inch Liquid Retina HD display",
        chip: "A13 Bionic chip with 4-core GPU",
        camera: "Dual 12MP Ultra Wide and Wide cameras",
        battery: "Up to 17 hours video playback",
        water: "IP68 water resistance",
      },
    },
    {
      id: "iphone-15-pro",
      name: "Apple iPhone 15 Pro",
      category: "iPhone",
      description:
        "iPhone 15 Pro. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.",
      price: 999.0,
      inStock: true,
      rating: 4.9,
      reviews: 1523,
      images: ["/iphone-15-pro-main.png"],
      thumbnails: ["/iphone-15-pro-1.png", "/iphone-15-pro-2.png"],
      storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
      colors: [
        "Natural Titanium",
        "Blue Titanium",
        "White Titanium",
        "Black Titanium",
      ],
      specifications: {
        display: "6.1-inch Super Retina XDR display with ProMotion",
        chip: "A17 Pro chip",
        camera: "Pro camera system with 48MP Main",
        battery: "Up to 23 hours video playback",
        material: "Titanium design",
      },
    },
    {
      id: "macbook-air-m2",
      name: 'MacBook Air 13" M2',
      category: "Mac",
      description:
        "Supercharged by M2 chip. The redesigned MacBook Air is more portable than ever and delivers exceptional speed and power efficiency.",
      price: 1099.0,
      inStock: true,
      rating: 4.8,
      reviews: 3421,
      images: ["/macbook-air-m2-main.jpg"],
      thumbnails: ["/macbook-air-m2-1.jpg", "/macbook-air-m2-2.jpg"],
      storage: ["256 GB", "512 GB", "1 TB", "2 TB"],
      colors: ["Midnight", "Starlight", "Space Gray", "Silver"],
      specifications: {
        display: "13.6-inch Liquid Retina display",
        chip: "Apple M2 chip",
        memory: "8GB unified memory",
        battery: "Up to 18 hours battery life",
        weight: "2.7 pounds",
      },
    },
    {
      id: "ipad-pro-11",
      name: 'iPad Pro 11"',
      category: "iPad",
      description:
        "iPad Pro with the M2 chip. The ultimate iPad experience with the most advanced technology.",
      price: 799.0,
      inStock: true,
      rating: 4.8,
      reviews: 1876,
      images: ["/ipad-pro-11-main.jpg"],
      thumbnails: ["/ipad-pro-11-1.jpg", "/ipad-pro-11-2.jpg"],
      storage: ["128 GB", "256 GB", "512 GB", "1 TB", "2 TB"],
      colors: ["Space Gray", "Silver"],
      specifications: {
        display: "11-inch Liquid Retina display",
        chip: "Apple M2 chip",
        camera: "12MP Wide camera",
        connectivity: "Wi-Fi 6E and 5G cellular",
        pencil: "Apple Pencil (2nd generation) support",
      },
    },
    {
      id: "airpods-pro-2",
      name: "AirPods Pro (2nd generation)",
      category: "AirPods",
      description:
        "Rebuilt from the sound up. AirPods Pro feature up to 2x more Active Noise Cancellation, Adaptive Transparency, and Personalized Spatial Audio.",
      price: 249.0,
      inStock: true,
      rating: 4.9,
      reviews: 5623,
      images: ["/airpods-pro-2-main.jpg"],
      thumbnails: ["/airpods-pro-2-1.jpg", "/airpods-pro-2-2.jpg"],
      colors: ["White"],
      specifications: {
        anc: "Up to 2x more Active Noise Cancellation",
        battery: "Up to 6 hours listening time",
        chip: "Apple H2 chip",
        audio: "Adaptive Audio and Personalized Spatial Audio",
        case: "MagSafe Charging Case with speaker",
      },
    },
    {
      id: "apple-watch-series-9",
      name: "Apple Watch Series 9",
      category: "Watch",
      description:
        "Our most powerful chip ever. A magical new way to use your watch without touching the screen. A brighter display.",
      price: 399.0,
      inStock: true,
      rating: 4.7,
      reviews: 2134,
      images: ["/apple-watch-series-9-main.jpg"],
      thumbnails: [
        "/apple-watch-series-9-1.jpg",
        "/apple-watch-series-9-2.jpg",
      ],
      sizes: ["41mm", "45mm"],
      colors: ["Midnight", "Starlight", "Silver", "Pink", "Red"],
      bands: ["Sport Band", "Sport Loop", "Braided Solo Loop", "Leather Link"],
      specifications: {
        display: "Always-On Retina display",
        chip: "S9 SiP",
        health: "Blood Oxygen and ECG apps",
        fitness: "Advanced workout metrics",
        battery: "Up to 18 hours",
      },
    },
    {
      id: "mac-mini-m2",
      name: "Mac mini M2",
      category: "Mac",
      description:
        "More muscle. More hustle. The new Mac mini with M2 and M2 Pro brings incredible performance and versatility.",
      price: 599.0,
      inStock: true,
      rating: 4.6,
      reviews: 987,
      images: ["/mac-mini-m2-main.jpg"],
      thumbnails: ["/mac-mini-m2-1.jpg", "/mac-mini-m2-2.jpg"],
      storage: ["256 GB", "512 GB", "1 TB", "2 TB"],
      memory: ["8GB", "16GB", "24GB"],
      specifications: {
        chip: "Apple M2 chip",
        ports: "Two Thunderbolt 4 ports, HDMI, USB-A",
        connectivity: "Wi-Fi 6E and Gigabit Ethernet",
        memory: "Up to 24GB unified memory",
        dimensions: "7.7 x 7.7 x 1.4 inches",
      },
    },
    {
      id: "iphone-14-pro-max",
      name: "Apple iPhone 14 Pro Max",
      category: "iPhone",
      description:
        "iPhone 14 Pro Max. The ultimate iPhone with Dynamic Island, Always-On display, and the most advanced Pro camera system.",
      price: 1099.0,
      originalPrice: 1199.0,
      discount: 8,
      inStock: true,
      rating: 4.8,
      reviews: 3567,
      images: ["/iphone-14-pro-max-main.png"],
      thumbnails: ["/iphone-14-pro-max-1.png", "/iphone-14-pro-max-2.png"],
      storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
      colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
      specifications: {
        display: "6.7-inch Super Retina XDR display with ProMotion",
        chip: "A16 Bionic chip",
        camera: "Pro camera system with 48MP Main",
        battery: "Up to 29 hours video playback",
        material: "Surgical-grade stainless steel",
      },
    },
  ],
  categories: [
    {
      id: "iphone",
      name: "iPhone",
      description: "The ultimate smartphone experience",
      image: "/images/category-iphone.jpg",
    },
    {
      id: "mac",
      name: "Mac",
      description: "Supercharged for pros and everyday users",
      image: "/images/category-mac.jpg",
    },
    {
      id: "ipad",
      name: "iPad",
      description: "Touch, draw, and type on the most advanced display",
      image: "/images/category-ipad.jpg",
    },
    {
      id: "watch",
      name: "Apple Watch",
      description: "The ultimate device for a healthy life",
      image: "/images/category-watch.jpg",
    },
    {
      id: "airpods",
      name: "AirPods",
      description: "Share the sound you love",
      image: "/images/category-airpods.jpg",
    },
  ],
  featuredProducts: ["iphone-15-pro", "macbook-air-m2", "airpods-pro-2"],
  dealsOfTheDay: ["iphone-14", "iphone-14-pro-max"],
};

export default appData;
